#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "No file name specified"
  echo "Usage: extract <filename>"
else
  if [ -f $1 ] ; then
    case $1 in
      *.bz2) bunzip2 ../$1 ;;
      *.exe) cabextract ../$1 ;;
      *.gz) gunzip ../$1 ;;
      *.lzma) unlzma ../$1 ;;
      *.rar) unrar x -ad ../$1 ;;
      *.tar) tar xvf ../$1 ;;
      *.tar.bz2) tar xvjf ../$1 ;;
      *.tar.gz) tar xvzf ../$1 ;;
      *.tar.xz) tar xvJf ../$1 ;;
      *.tbz2) tar xvjf ../$1 ;;
      *.tgz) tar xvzf ../$1 ;;
      *.xz) unxz ../$1 ;;
      *.Z) uncompress ../$1 ;;
      *.zip) unzip ../$1 ;;
      *.7z) 7z x ../$1 ;;
      *) echo "extract: '$1' - Archive type not known" ;;
    esac
  else
    echo "$1 - file does not exist"
  fi
fi
