#!/usr/bin/env bash

read -e -p "Enter your git username: " GIT_USER
read -e -p "Enter your git email address: " GIT_EMAIL

git config --global color.ui true

git config --global diff.tool vimdiff
git config --global difftool.prompt false
git config --global alias.d difftool

git config --global user.name "$GIT_USER"
git config --global user.email "$GIT_EMAIL"
git config --global core.excludesfile "$HOME/.gitignore"

